### ISSUE TITLE
新建或者编辑的一个错误处理

### ISSUE THREAD

**Issue by cjfff** [FEMessage/el-data-table#100]
**Is your feature request related to a problem? Please describe.**
现在有这么一个场景，就是比如一个新建的场景，使用了 `el-data-table` 中的 `form` 功能，然后根据 `crud` 的 `c` 去进行一个 `post` 请求，但是由于一些原因，后端判断这个名字重复，这个 `post` 请求没有成功，但也没有任何的提示，只是默默的失败了，

ps: 后端失败现在只给出了一个 `resetful code` 不为 0, 不是 `http status code`, 全局拦截不好做。

**Describe the solution you'd like**
我希望有一个可以传入错误处理的方式，比如我传入一个 `onError` 或者一个 `onSucessCallBack` 方法去处理操作失败的问题。

**Additional context**
提供后端 `response` 格式。
![image](https://user-images.githubusercontent.com/20502762/57704702-0786f300-7695-11e9-8028-c4edce1b279a.png)

**Comment by levy9527** [comment]
这个建议从框架层面处理。参考：https://github.com/levy9527/nuxt-element-dashboard/pull/7
