### ISSUE TITLE
[TODO] 期望能在headerButtons后增加插槽,部分ui设计可能会用到一些滑块或其他非按钮元素

### ISSUE THREAD

**Issue by jmzyang** [FEMessage/el-data-table#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donaldshen** [comment]
期望先提出具体的应用场景

**Comment by levy9527** [comment]
可以加入todoList
