### ISSUE TITLE
prop.customQuery被组件内部修改了

### ISSUE THREAD

**Issue by cjfff** [FEMessage/el-data-table#105]
**Describe the bug**
源码中的resetSearch方法里，直接修改了customQuery属性

**Comment by donaldshen** [comment]
**Describe the bug**
resetSearch里，会将customQuery重设成第一次传进来的值。但用户可能会对customQuery先设个初始值然后用接口返回的值去更新它。现在用户点击reset按钮后，customQuery的值丢失并被更新为初始值。
