### ISSUE TITLE
分页里面的 mock 接口bug

### ISSUE THREAD

**Issue by zhangrenjian** [FEMessage/el-data-table#111]
我看了一下源码，对分页条数的数组是有支持自定义的，传了一个 :paginationSizes="pageArr"   pageArr = [1,5,10] 选了每页 1 条，接口请求的时候参数也传了 size:1， 结果返回 3条数据。
一点建议：从组件的通用性，建议去掉 默认的修改按钮，让用户之间传需要使用的按钮就行了

**Comment by donaldshen** [comment]
“默认的修改按钮”是指什么？你是在说pagination组件需要修改还是操作列的那个修改按钮问题？

案例中的mock接口设计满足案例需要即可。

**Comment by levy9527** [comment]
mock接口这样的：
传page=1，会返回随机的数据，比如3条
传page=10, 仍会返回随机的数据，比如3条。

所以这其实是mock接口的特性。

**Comment by levy9527** [comment]
感谢你的建议。由于组件的初衷是快速curd，如果去掉修改，就只有crd，初初衷违背了。
