### ISSUE TITLE
【功能问题】使用el-table自带的事件如何处理

### ISSUE THREAD

**Issue by beautycss** [FEMessage/el-data-table#116]
你好，我已经使用了你们的组件做好了数据渲染，都挺好的。

现在想使用el-table自带的事件row-click事件做点击行的处理，发现无法传递到table组件。
你们提供了一个tableAttrs是传递数据的，那请问事件如何传递过去？

我觉得使用表格自带的一些事件应该是基础需求，考虑扩展一下，或者把el-table自带的事件加上去？

**Comment by donaldshen** [comment]
你可以通过直接引用内部el-table的方式来添加事件监听。比如你为el-data-table添加`ref="dataTable"`属性，你就可以这样子`this.$refs.dataTable.$refs.table.$on('row-click', handler)`

**Comment by beautycss** [comment]
试过了可以，谢谢。👍

**Comment by levy9527** [comment]
感谢你的认可 @beautycss
