### ISSUE TITLE
两个 data-table 在同一个页面使用时，searchForm 部分输入不能重置

### ISSUE THREAD

**Issue by lianghx-319** [FEMessage/el-data-table#119]
**Before**
![image](https://user-images.githubusercontent.com/27187946/59015253-22eab580-8871-11e9-970b-61cf5530ba37.png)
![201903126](https://user-images.githubusercontent.com/27187946/59015265-27af6980-8871-11e9-95bc-0046bfe9dd9d.gif)

**After**
![image](https://user-images.githubusercontent.com/27187946/59015310-46156500-8871-11e9-88d9-8448b26c7b69.png)
![201903127](https://user-images.githubusercontent.com/27187946/59015350-5b8a8f00-8871-11e9-9fd1-da17d4ab9128.gif)

**Description**
当一个页面中使用 v-if 条件渲染 table 时，searchForm 重置的功能部分丢失。但是给每个 table 加了 key 属性之后就正常了

**Comment by donaldshen** [comment]
没什么好办法可以在组件内解决。现在没法确认vue的vnode复用机制还影响到哪些组件的功能。建议此类情况都通过key属性来规避问题
