### ISSUE TITLE
form 没有详细配置介绍

### ISSUE THREAD

**Issue by 738579138** [FEMessage/el-data-table#124]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donaldshen** [comment]
https://femessage.github.io/el-data-table/
![image](https://user-images.githubusercontent.com/19591950/59262875-aa219a00-8c72-11e9-916e-3755287fb178.png)
请问你指的是这个prop的配置吗？你希望文档如何完善？

**Comment by 738579138** [comment]
我想问的是，比如新增按钮，点击的时候如何弹出我自定义的弹窗呢？

**Comment by donaldshen** [comment]
> 我想问的是，比如新增按钮，点击的时候如何弹出我自定义的弹窗呢？

`form`的值会直接传给`el-form-renderer`的`content`属性，[文档参考](https://femessage.github.io/el-form-renderer/#/Components?id=src)，[案例链接](https://femessage.github.io/el-form-renderer/#!/basic/1)
![image](https://user-images.githubusercontent.com/19591950/59330284-9eda7700-8d23-11e9-86f8-538ee26c0c03.png)

**Comment by 738579138** [comment]
el-data-table 中的新增按钮如何跟 el-form-renderer 关联在一起呢？

**Comment by donaldshen** [comment]
新增按钮会打开一个`el-dialog`，dialog内部则是用`el-form-renderer`来渲染的。具体可看源码

**Comment by 738579138** [comment]
谢谢，原来是加了form 插槽了
