### ISSUE TITLE
需要添加一个设置 el-form-render 组件的 prop

### ISSUE THREAD

**Issue by xrr2016** [FEMessage/el-data-table#130]
目前直接使用 el-data-table 无法向内部的 el-form-render 传递属性，导致无法设置 el-form 的属性。

期望有一个属性可以设置 el-form 的属性，比如 renderAttrs

![image](https://user-images.githubusercontent.com/18013127/59488567-864c9700-8eb2-11e9-8937-d986604c10eb.png)

**Comment by donaldshen** [comment]
可以的。你拿到el-data-table的引用dataTable后，只需`dataTable.$refs.searchForm.labelWidth='100px'`。任何prop都可以如此处理
