### ISSUE TITLE
有完整例子吗

### ISSUE THREAD

**Issue by chigco** [FEMessage/el-data-table#14]
照着test的内容放到项目中，一直显示暂无数据

**Comment by levy9527** [comment]
你可以看看storybook的示例，调一下mock api的地址
显示没有数据，是因为，`url`配置的是api地址，table会根据这个地址发送请求，如果你没有这个api，当然没有数据了。

**Comment by chigco** [comment]
你测试的例子给的地址：http://levy.ren:3000/mock/11/levy/api/v1/generatorUsers 是有数据返回的

**Comment by levy9527** [comment]
可以啊。
```js
data () {
  return {
    columns: []
  }
},
methods: {
  eventHandler () {
    this.columns = xxx
  }
}
```

**Comment by levy9527** [comment]
更多完整的例子，请参考stories文件夹

https://github.com/FEMessage/el-data-table/tree/master/stories
