### ISSUE TITLE
searchForm的属性可以自定义么

### ISSUE THREAD

**Issue by little-eight-china** [FEMessage/el-data-table#141]
比如最后的url可能是i&id=1&name=1,现在我想通过一些操作改成&map={id=1,name=1}，可以实现不

**Comment by donaldshen** [comment]
1. 需求场景是什么？
2. 想要效果是什么？现在的query的pattern是q=a~1,b~2，你希望的pattern是q={a=1,b=2}？
3. 期望的操作是啥？table接受两个新prop？一个定义如何格式化query，另一个定义如何解析query？你可以参考源码中src/utils/query.js

**Comment by levy9527** [comment]
可以使用 `customQuery`，往url传自定义参数
