### ISSUE TITLE
修改的请求应该改成PATCH

### ISSUE THREAD

**Issue by little-eight-china** [FEMessage/el-data-table#142]
修改建议不使用PUT是因为通常只是部分字段进行了更新操作

**Comment by donaldshen** [comment]
1. PATCH 语义上更符合
2. PUT 能指示这次请求具有幂等性
3. 两者实际功能相同，除了造成breaking change之外改动没有意义

**Comment by levy9527** [comment]
这个跟后端接口约定有关。也有修改使用 `patch` 的，如果目前要使用table来实现的话，可以自定义onEdit props。
