### ISSUE TITLE
操作列的额外按钮的type设置无效果

### ISSUE THREAD

**Issue by little-eight-china** [FEMessage/el-data-table#144]
设置了一个hello的按钮，但是显示的type依然是text，从图也可看到删除的按钮也异常了。
```
 extraButtons: [
        {
          type: 'danger',
          text: 'hello',
          atClick (row) {
            alert(row.name)
          }
        }
      ]
```
![image](https://user-images.githubusercontent.com/27406442/59914475-10fe3a80-944d-11e9-8043-a122fceaaec4.png)

版本是1.4.2

**Comment by donaldshen** [comment]
操作列的按钮样式已经重构过了 #137 。type属性不会直接传给el-button，而仅是用来渲染颜色。
具体表现会类似于el-link的效果。
下个版本会发布这个改动:)

**Comment by donaldshen** [comment]
1.5.0版已修复了，你可以体验一下

**Comment by levy9527** [comment]
```sh
yarn upgrade el-data-table --latest
```
