### ISSUE TITLE
支持对单元格的样式设置么

### ISSUE THREAD

**Issue by little-eight-china** [FEMessage/el-data-table#146]
我在readme中看到可以自定义样式，但是好像并没找到相关的入口，所以我想实现下图这种，有入口不
![image](https://user-images.githubusercontent.com/27406442/59999806-73497c00-9695-11e9-8b80-4e8875e9bd07.png)

**Comment by mmaotai** [comment]
> 我在readme中看到可以自定义样式，但是好像并没找到相关的入口，所以我想实现下图这种，有入口不
> ![image](https://user-images.githubusercontent.com/27406442/59999806-73497c00-9695-11e9-8b80-4e8875e9bd07.png)

怎么操作的 贴个链接?  

另表格某一列为switch   支持点击修改的 有用例吗

**Comment by gd4Ark** [comment]
@mmaotai https://frontend-infra.deepexi.com/#/material/el-data-table?file=formatter.md&q=q~%22femessage%22,size~20,page~1,
