### ISSUE TITLE
在点击表格的查看按钮时，会报错

### ISSUE THREAD

**Issue by little-eight-china** [FEMessage/el-data-table#148]
如图，文档的在线例子也会报这样的错误

![image](https://user-images.githubusercontent.com/27406442/60074603-e7e3ef80-9755-11e9-9024-d858e7b40e74.png)

可以避免么

**Comment by donaldshen** [comment]
请问具体是哪个例子？目前好像没有案例是开启hasView的（看来要补充一个）。尝试过在basic里开启hasView = true，“查看”按钮没有报错

**Comment by little-eight-china** [comment]
@donaldshen 
说错，是点击basic例子的修改，但我自己使用的查看按钮是一样的报错信息，怀疑是同一个问题

![image](https://user-images.githubusercontent.com/27406442/60082123-bf63f180-9765-11e9-8f7e-8354ee6a5d34.png)

神奇的事before-confirm的修改按钮又没报错，对比俩者代码，没有明显不同之处

![image](https://user-images.githubusercontent.com/27406442/60082261-f508da80-9765-11e9-9c6b-5fecb88d6c92.png)

**Comment by donaldshen** [comment]
> @donaldshen
> 说错，是点击basic例子的修改，但我自己使用的查看按钮是一样的报错信息，怀疑是同一个问题
> 
> ![image](https://user-images.githubusercontent.com/27406442/60082123-bf63f180-9765-11e9-8f7e-8354ee6a5d34.png)
> 
> 神奇的事before-confirm的修改按钮又没报错，对比俩者代码，没有明显不同之处
> 
> ![image](https://user-images.githubusercontent.com/27406442/60082261-f508da80-9765-11e9-9c6b-5fecb88d6c92.png)

你和我的是同一个链接吗？https://femessage.github.io/el-data-table/#!/basic/1
或提供一下你的💻系统信息

**Comment by little-eight-china** [comment]
@donaldshen 
不是，
https://femessage.github.io/el-data-table/#/Demo?id=basic

**Comment by little-eight-china** [comment]
@donaldshen  
原来是引用的依赖错了，el-form-renderer 改成 @femessage/el-form-renderer 即可

**Comment by levy9527** [comment]
> @donaldshen
> 原来是引用的依赖错了，el-form-renderer 改成 @femessage/el-form-renderer 即可

请问，你是怎么会引用到 `el-form-renderer` 的，是文档哪里没说明清楚吗 😅
