### ISSUE TITLE
希望能对新增弹框el-dialog，设置element-ui的属性Attributes

### ISSUE THREAD

**Issue by wuyanping** [FEMessage/el-data-table#149]

**Comment by wuyanping** [comment]
需要这个功能的场景：目前el-data-table的弹框都是点击蒙层就能关闭了，但是我想点击蒙层，不关闭；element-ui的el-dialog提供了这个属性，是否能提供一个属性来设置el-data-table的弹框

**Comment by donaldshen** [comment]
感觉有必要重新梳理`el-data-table`组件内部的模块，让用户可以简单直接地对原生element组件设置属性和监听事件。
1. 目前大致有四个组件：`search-form`, `table`, `pagination`和`dialog`
2. 增加八个props：`searchFormProps`, `searchFormListeners`, `tableProps`, ……
3. 以`search-form`的两个新增props举例，`searchFormProps`会直接`v-bind`到`search-form`的根节点上，`searchFormListeners`会直接`v-on`到`search-form`的根节点上

**Comment by wuyanping** [comment]
这个方案需要多久可以完成呢？

**Comment by levy9527** [comment]
这个可能是在2.0版本去实现，需要规划下🤔

**Comment by donaldshen** [comment]
`this.$refs.dataTable.$children.find(c=>c.$options._componentTag==='el-dialog').closeOnClickModal=false`
这种方式可以用

**Comment by donaldshen** [comment]
same as #130

**Comment by levy9527** [comment]
see #201 代码已合并。新版本即可使用，请留意发版本通知
