### ISSUE TITLE
编辑的时候如何指定自定义主键？

### ISSUE THREAD

**Issue by ll1211** [FEMessage/el-data-table#15]
编辑的时候如何指定自定义主键？

**Comment by chenEdgar** [comment]
能说明你的具体需求吗？

**Comment by levy9527** [comment]
你的意思是，id是xx， 编辑时，put请求url带上的不是id，而xx，是这样吗？
如果是，目前还不支持，这两天改改

**Comment by levy9527** [comment]
https://github.com/FEMessage/el-data-table/pull/17
