### ISSUE TITLE
feat: clearSelection

### ISSUE THREAD

**Issue by donaldshen** [FEMessage/el-data-table#152]
## Why
用户有通过clearSelection清空多选状态的需求。但data-table有跨页多选的逻辑，这时用户再调用el-table的clearSelection方法，就没法取得预期效果

## How
1. 实现data-table自己的clearSelection方法
2. 文档中说明：当开启persist-selection时，用户不要使用el-table的clearSelection、toggleRowSelection和toggleAllSelection方法

**Comment by lianghx-319** [comment]
- 我觉得可以将这些方法也继承到data-table
- 然后多选清空变为 clearAllSelection 
- 调用起来会不会方便一点
- 这样也方便根据 persist-selection 的状态给出 warning 或者兼容操作

**Comment by lianghx-319** [comment]
Duplicate of #151
