### ISSUE TITLE
两个以上data-table在同一个页面使用时，切换table分页没有初始化，比如一个table当前切换到了第二页，点击第二个table，仍然在第二页，期望应该在第一页

### ISSUE THREAD

**Issue by huleilw** [FEMessage/el-data-table#155]
**Describe the bug**

**Screenshots**

**To Reproduce**

**Expected behavior**

**environment information:**

**Comment by levy9527** [comment]
使用 `saveQuery=false` ，则table不受 url 的 query 影响。
