### ISSUE TITLE
是否有配置生成的网站

### ISSUE THREAD

**Issue by 738579138** [FEMessage/el-data-table#158]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 738579138** [comment]
就像git 的下面介绍里面有一个配置的截图，我们配置好，然后生成json 的网站

**Comment by donaldshen** [comment]
1. 请按模板提feature
2. 那个配置的截图是啥？table和git和json有什么关系？
