### ISSUE TITLE
header buttons是否可以支持dropdown下拉选择

### ISSUE THREAD

**Issue by linrunzheng** [FEMessage/el-data-table#175]
**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/20603896/61508429-64e44b00-aa1c-11e9-9b78-b7aecd6acdbd.png)

当按钮越来越多后，希望可以收起来

![image](https://user-images.githubusercontent.com/20603896/61508461-978e4380-aa1c-11e9-96b2-978ebce42963.png)

**Comment by donaldshen** [comment]
same as #103

**Comment by levy9527** [comment]
6啊，这个需求😂
