### ISSUE TITLE
多选框提示: <transition-group> children must be keyed: <ElTag>

### ISSUE THREAD

**Issue by yanye321** [FEMessage/el-data-table#176]
多选框提示: <transition-group> children must be keyed: <ElTag>,  
多选框的options是 ajax请求后, setOptions添加的,  请问怎样绑定key?

**Comment by donaldshen** [comment]
啥？
场景是啥？
transition-group？ElTag？el-data-table内部没有使用这些元素

**Comment by yanye321** [comment]
> 啥？
> 场景是啥？
> transition-group？ElTag？el-data-table内部没有使用这些元素

不好意思, 没描述清楚.  是el-form-renderer里面的报错.

```
forms: [
          {
            type: 'select',
            id: 'test_item',
            label: 'test_item',
            el: { filterable: true, multiple: true, 'multiple-limit': 2 },
            options: [{
              value: '选项1',
              label: '黄金糕'
            }, {
              value: '选项2',
              label: '双皮奶'
            }, {
              value: '选项3',
              label: '蚵仔煎'
            }, {
              value: '选项4',
              label: '龙须面'
            }, {
              value: '选项5',
              label: '北京烤鸭'
            }]
          }
]
```
forms里面使用多选框,  关闭或提交, console会报错`<transition-group> children must be keyed: <ElTag>`
再次打开form表单, 多选框会异常, 只能勾选一个.

console报错如下:
```
[Vue warn]: <transition-group> children must be keyed: <ElTag>
  | warn | @ | vue.runtime.esm.js:594
-- | -- | -- | --
  | render | @ | vue.runtime.esm.js:8237
  | Vue._render | @ | vue.runtime.esm.js:3517
  | updateComponent | @ | vue.runtime.esm.js:4035
  | get | @ | vue.runtime.esm.js:4448
  | run | @ | vue.runtime.esm.js:4523
  | flushSchedulerQueue | @ | vue.runtime.esm.js:4279
  | (anonymous) | @ | vue.runtime.esm.js:1955
  | flushCallbacks | @ | vue.runtime.esm.js:1881
  | Promise.then (async) |   |  
  | timerFunc | @ | vue.runtime.esm.js:1908
  | nextTick | @ | vue.runtime.esm.js:1965
  | queueWatcher | @ | vue.runtime.esm.js:4371
  | update | @ | vue.runtime.esm.js:4513
  | notify | @ | vue.runtime.esm.js:705
  | reactiveSetter | @ | vue.runtime.esm.js:1030
  | proxySetter | @ | vue.runtime.esm.js:4600
  | resetInputWidth | @ | element-ui.common.js:8762
  | handleResize | @ | element-ui.common.js:8765
  | (anonymous) | @ | resize-event.js:8
  | resizeHandler | @ | resize-event.js:7
```

**Comment by xrr2016** [comment]
经过测试发现关闭对话框后 el-data-table 执行了 el-form-renderer 的 resetFields 函数导致

```js
 dialogVisible: function(val, old) {
      if (!val) {
        this.isNew = false;
        this.isEdit = false;
        this.isView = false;
        this.confirmLoading = false;

        this.$refs[dialogForm].resetFields();  // 这行代码的问题
      }
 },
```

**Comment by xrr2016** [comment]
> > 啥？
> > 场景是啥？
> > transition-group？ElTag？el-data-table内部没有使用这些元素
> 
> 不好意思, 没描述清楚. 是el-form-renderer里面的报错.
> 
> ```
> forms: [
>           {
>             type: 'select',
>             id: 'test_item',
>             label: 'test_item',
>             el: { filterable: true, multiple: true, 'multiple-limit': 2 },
>             options: [{
>               value: '选项1',
>               label: '黄金糕'
>             }, {
>               value: '选项2',
>               label: '双皮奶'
>             }, {
>               value: '选项3',
>               label: '蚵仔煎'
>             }, {
>               value: '选项4',
>               label: '龙须面'
>             }, {
>               value: '选项5',
>               label: '北京烤鸭'
>             }]
>           }
> ]
> ```
> 
> forms里面使用多选框, 关闭或提交, console会报错`<transition-group> children must be keyed: <ElTag>`
> 再次打开form表单, 多选框会异常, 只能勾选一个.
> 
> console报错如下:
> 
> ```
> [Vue warn]: <transition-group> children must be keyed: <ElTag>
>   | warn | @ | vue.runtime.esm.js:594
> -- | -- | -- | --
>   | render | @ | vue.runtime.esm.js:8237
>   | Vue._render | @ | vue.runtime.esm.js:3517
>   | updateComponent | @ | vue.runtime.esm.js:4035
>   | get | @ | vue.runtime.esm.js:4448
>   | run | @ | vue.runtime.esm.js:4523
>   | flushSchedulerQueue | @ | vue.runtime.esm.js:4279
>   | (anonymous) | @ | vue.runtime.esm.js:1955
>   | flushCallbacks | @ | vue.runtime.esm.js:1881
>   | Promise.then (async) |   |  
>   | timerFunc | @ | vue.runtime.esm.js:1908
>   | nextTick | @ | vue.runtime.esm.js:1965
>   | queueWatcher | @ | vue.runtime.esm.js:4371
>   | update | @ | vue.runtime.esm.js:4513
>   | notify | @ | vue.runtime.esm.js:705
>   | reactiveSetter | @ | vue.runtime.esm.js:1030
>   | proxySetter | @ | vue.runtime.esm.js:4600
>   | resetInputWidth | @ | element-ui.common.js:8762
>   | handleResize | @ | element-ui.common.js:8765
>   | (anonymous) | @ | resize-event.js:8
>   | resizeHandler | @ | resize-event.js:7
> ```

已修复问题，请将 @femessage/el-form-renderer 更新至最新版本

**Comment by levy9527** [comment]
这个问题其实是  @femessage/el-form-renderer 的 bug， 已发布了 版本， 更新即可。具体 release 可查看这里：https://github.com/FEMessage/el-form-renderer/releases/tag/v1.10.1

这里就先关闭了。

**Comment by donaldshen** [comment]
重现步骤：
1. 在 el-form-renderer 中操作（el-form 没有这个问题，待会讲
2. 使用 el-select，开启 multiple
3. 不传入 default 值
4. 调用 resetFields，即可重现

原因是：
1. el-select 在 created 时，会检查传入的 value 是否合法。比如如果传入了 undefined，会立即`$emit('input', this.multiple ? [] : '')`。
2. el-form-item 在 mounted 时，会存一份 initialValue。resetField 时会用到
3. 而 el-form-renderer 传入值时错过了这个时机，导致 el-form-item 记录的 initialValue = undefined，进而 resetFields 时传入了不合法的值
