### ISSUE TITLE
新增问题

### ISSUE THREAD

**Issue by chigco** [FEMessage/el-data-table#18]
我点击新增或是编辑按钮后，
怎么窗口在后，蒙层在前？顺序不对啊？

**Comment by chenEdgar** [comment]
为了方便我们定位这个问题，你能给一个在线的demo吗？
包括浏览器环境等

**Comment by chigco** [comment]
我这边发现是需要添加一个:append-to-body="true"在el-dialog中。那么，我如果来修改呢？

**Comment by chenEdgar** [comment]
方便给出完整demo示例吗?

或者查看在项目stories目录中，查看使用示例

**Comment by chigco** [comment]
我想修改这个el-data-table怎么修改再进行编译引用呢？

**Comment by levy9527** [comment]
你把源码copy过去，放到你项目里就可以了
