### ISSUE TITLE
👨🏻‍💻👩‍💻欢迎加入 FEMessage 支持交流群

### ISSUE THREAD

**Issue by levy9527** [FEMessage/el-data-table#181]
扫描二维码加入 钉钉 讨论组

![image](https://user-images.githubusercontent.com/9384365/61931590-9c6e6c80-afb3-11e9-9c1f-0d61313a1bfb.png)

**Comment by LiuG-lynx** [comment]
这个二维码过期了额

**Comment by levy9527** [comment]
呃，好吧。

**Comment by 2686521696** [comment]
@levy9527 二维码过期了，可以重新发一个吗

**Comment by levy9527** [comment]
@LiuG-lynx @2686521696 不好意思，已更新。

**Comment by levy9527** [comment]
也可以点击链接加入：[公瑾邀请你加入钉钉群聊FEMessage开源交流群，点击进入查看详情 ](https://qr.dingtalk.com/action/joingroup?code=v1,k1,MhXFK8lmjg5HqzNCR2VodZEt59WLwTwM6TrAmerdq6M=&_dt_no_comment=1&origin=11)

**Comment by eriollee** [comment]
> @LiuG-lynx @2686521696 不好意思，已更新。
已经过期了 点击进去是钉钉官网

**Comment by levy9527** [comment]
哭死，这钉钉跟微信一样会过期啊，那算了，有事直接github流言吧
