### ISSUE TITLE
hasSearchForm controller wanted

### ISSUE THREAD

**Issue by zcqno1** [FEMessage/el-data-table#182]
**Is your feature request related to a problem? Please describe.**
Sometime I just want a clean table. No search form. No NEW button. No DELETE button and etc..
Set the config not to render those things. OK, no form and no buttons anymore. 
But it still renders the wrapper component which has a `margin-bottom: 22px`, making the table `22px` to its top.
![image](https://user-images.githubusercontent.com/11766057/61951693-5a115380-afe4-11e9-8dd2-b7e0b2d5b771.png)

**Describe the solution you'd like**
I don't want to get rid of the `22px` gap on the top of the table. Or, just no render the extra form.

**Describe alternatives you've considered**
If providing a prop `hasSearchForm` to control whether rendering the search form, that's great.
By the way, perhaps the dialog forms have no need either. Maybe a prop `hasDialogForm` is OK too.

**Additional context**

**Comment by donaldshen** [comment]
> Describe the solution you'd like
I don't want to get rid of the 22px gap on the top of the table. Or, just no render the extra form.

I think you mean you want to get rid of that 22px gap, right?

Anyway, when `!hasNew && !hasDelete && !headerButtons.length` is true, there will be no header anymore, including that 22px gap. Try that in this [preview](https://femessage.github.io/el-data-table/#!/basic/1)

**Comment by zcqno1** [comment]
Yeah, setting `hasDelete: false` works. I just set `hasOperation: false` and found no extra BUTTONs, then I thought there's no need to set `hasDelete: false`. 
If I set a `selection` column, the DELETE BUTTON for bulk operation shows again on the top, which explains the `hasDelete: false` logic in this case.
