### ISSUE TITLE
希望可以自定义查询请求过程

### ISSUE THREAD

**Issue by HydrogenPan19** [FEMessage/el-data-table#185]
现在配置 `url` 就可以自动 list ，里面直接调用 `this.$axios` ，这样不好吧。。。，不能要求用户都用这个吧。。

虽然我也是用 axios，但有的时候 需要对请求做公共处理（只是列表的 list 公共处理，所有不能放在 axios 的拦截器）。

另外，有时候要对对 list 回来的数据做一些处理，依赖 el 的 formatter 比较受限。

最后，最重要一点，有的 list 接口是 **`POST`** 的！！！

希望可以自定义查询请求

**Comment by levy9527** [comment]
请问，假设支持了这个功能，理想状态下，代码应该怎么写呢？

给一下期望代码，我们好评估如何实现。

**Comment by HydrogenPan19** [comment]
其实像 onEdit onDelete 这样支持配置一个函数，这些问题都好办了。

**Comment by levy9527** [comment]
你是想要 request 函数。不过，table 的本意是，让 RESTful 接口对接得更顺畅。

则：
- 则查询请求是 get 方法
- $axios 只是别名，可以在应用里写 Vue.prototype.$axios = request
- 数据处理，还是期望给提供相应代码

总的来说，很多时候问题的源头，是规范、是与人沟通，但因为用了组件，就期望组件来解决了。

**Comment by HydrogenPan19** [comment]
好吧，你说得有道理。
不过我这边就没办法了，对接的项目是已经有的，不能因为这个原因而去改服务端加另外的 web 端。

**Comment by HydrogenPan19** [comment]
关于数据处理，因为过了几个月，记得不是很清楚了，举一个例子代表处理过程。

表格行 有用户，但返回数据的数组中，用户字段，只是给一个 uid 的，
具体的用户数据是额外集中在 另一个对象中返回

返回数据结构
```
code: 0,
data: {
  list: [ ], // 表格数据, [{ uid: 'a123', ... }]
  user: {}, // uid 为 key 的 map
}
```

> 概括的话，就是每行显示的信息，需要额外处理才能得到最终数据。

el 的 formatter 只能得到 row ，处理不了。

**Comment by levy9527** [comment]
好的，不过，现在table比之前有个进步，就是支持 axios 配置了，不用修改公共的axios配置
