### ISSUE TITLE
开启saveQuery查询后点击页面后退或前进，组件可根据查询参数进行状态更新或退出页面

### ISSUE THREAD

**Issue by zcqno1** [FEMessage/el-data-table#186]
**Is your feature request related to a problem? Please describe.**
开启`saveQuery`查询后，点击页面后退或前进，组件内部没有触发相应的查询变化，而简单表现为 url 的变化

过程
1. 设置配置项 `saveQuery: true`
2. 对表格进行翻页或输入查询字段进行查询，此时页面 url 会加入相应的查询参数
3. 可重复步骤 2 若干次
4. 点击浏览器的后退（或前进，如果已后退过）
5. 结果仅表现为 url 的变动，页面无任何变化

PS：文档 [demo](https://serverless.deepexi.top/serverless-console/index.html#/material/el-data-table?file=save-query.md) 即可用于复现

**Describe the solution you'd like**
提供两种可选的浏览器前进/后退行为控制：
1. 表格组件根据相应的参数进行相应状态更新，即要 watch 查询参数的变化
2. 后退时退出当前表格所在页面，也即 url 保存查询参数表现为 `replace` 的效果

**Comment by levy9527** [comment]
@donaldshen 组件需要 mounted 时进行查询
