### ISSUE TITLE
希望能提供 default 插槽的相关示例和文档

### ISSUE THREAD

**Issue by tanshiqi** [FEMessage/el-data-table#190]
**Is your feature request related to a problem? Please describe.**
只有一句话“当extraButtons不满足需求时可以使用”

**Describe the solution you'd like**
试了下发现无法插入操作栏，希望能提供相关示例和文档，谢谢

**Describe alternatives you've considered**

**Additional context**

**Comment by donaldshen** [comment]
![image](https://user-images.githubusercontent.com/19591950/62531348-d9204a80-b874-11e9-98af-acde2466c1ad.png)

**Comment by tanshiqi** [comment]
感谢，原来还要包一个 el-table-column

**Comment by donaldshen** [comment]
参考这个：
https://element.eleme.cn/#/zh-CN/component/table#gu-ding-lie
