### ISSUE TITLE
使用使用自定义的搜索组件（slot-search),重置按钮无法清除Request URL中自定义的查询条件

### ISSUE THREAD

**Issue by binonxia** [FEMessage/el-data-table#195]
## Describe the bug
使用自定义的搜索组件（slot-search),重置按钮无法清除Request URL中自定义的查询条件

## To Reproduce
1. 输入自定义查询条件，点击查询，点击重置按钮
2. Request URL的自定义查询条件未完全清空

## Expected behavior
点击重置按钮，清空Request URL所有的查询条件

## environment information
 - Version [1.6.1]
 - OS: [macOs]
 - Browser [chrome]

**Comment by levy9527** [comment]
可以给个图片吗。我们复原下场景。

**Comment by donaldshen** [comment]
https://femessage.github.io/el-data-table/#/Demo/extra-query.sync
你说的是这个场景吗？

**Comment by levy9527** [comment]
#196 。

需要这样设置，我补充一下文档
```js
this.extraQuery.id = null
```

**Comment by levy9527** [comment]
see #206
