### ISSUE TITLE
使用el-data-table操作栏的删除，网络很慢的时候，删除弹窗的loading相互污染！

### ISSUE THREAD

**Issue by wuyanping** [FEMessage/el-data-table#198]
## Describe the bug
使用el-data-table操作栏的删除，网络很慢的时候，删除弹窗的loading相互污染！

## Screenshots
![image](https://user-images.githubusercontent.com/24385361/62753426-26cbcb80-ba9e-11e9-8418-7426a8587f7c.png)

## To Reproduce
1. table的第一条数据，点击删除，然后点击取消（由于网络很慢，这个时候还没删除成功）
2. 再点击table的第二条数据，点击删除，弹框的确定按钮一直还在loading。（由于网络很慢，这个时候table的第一条数据还没删除成功）

## Expected behavior
删除按钮的loading不应该相互污染

## environment information
 - Version ：el-data-table": "^1.7.0"
 - OS: widow
 - Browser ：chrome

**Comment by lianghx-319** [comment]
点击取消的时候也调用一下 `done()` 这样应该就可以了

**Comment by levy9527** [comment]
这个，网络没有响应，还是不进行下一步操作比较好吧

**Comment by donaldshen** [comment]
这个不好处理。
首先，messageBox全局只有一个实例。假设我们在messageBox关闭时一律清空loading状态，那么：
1. 你删除行a，开始loading，然后未等待请求返回就关闭messageBox
2. 你删除行b，开始loading，但此时删除a的请求返回了，并结束loading状态。这也不是我们想要的结果

综上，建议不要一项项删除，可以多选后再删除。
