### ISSUE TITLE
slot-form 如何获取数据

### ISSUE THREAD

**Issue by tanshiqi** [FEMessage/el-data-table#202]
## Describe the bug
form插槽用法好像无法获取当前记录的数据？
`<template v-slot:form="scope">{{ scope.name }}</template>`这样无效

**Comment by levy9527** [comment]
目前是无法获取的。加入下周的开发计划中。

**Comment by donaldshen** [comment]
期望获得哪些数据？

**Comment by eviIIt** [comment]
希望提供是用在什么地方. 目前 __盲猜__ 是期望获取el-form-renderer的value.

**Comment by tanshiqi** [comment]
我觉得至少应该要提供当前编辑数据的模型吧

**Comment by donaldshen** [comment]
> 我觉得至少应该要提供当前编辑数据的模型吧

请描述一个较完整的用法场景吧🤔

**Comment by tanshiqi** [comment]
> > 我觉得至少应该要提供当前编辑数据的模型吧
> 
> 请描述一个较完整的用法场景吧🤔，附代码

```
<el-data-table v-bind="$data">
            <template v-slot:form="scope">
                        这里可以用自定义组件编辑这条记录，比如 {{ scope.content }}
            </template>
</el-data-table>
```

**Comment by donaldshen** [comment]
id|name|操作列
---|---|---
123|mike|修改

就是你点击某一行的”修改“按钮，你希望这时slot-form里能获取该行的数据`{id:123,name:'mike'}`
那点击“新增”按钮的情况呢，这时传什么？

**Comment by tanshiqi** [comment]
我觉得用于自定义组件是一种场景，还有一种是用于更加复杂的表单布局，毕竟配置文件生成的是单列的布局，有些时候的表单可能需要网格化布局结合，甚至一些复杂的样式

**Comment by tanshiqi** [comment]
> id	name	操作列
> 123	mike	修改
> 就是你点击某一行的”修改“按钮，你希望这时slot-form里能获取该行的数据`{id:123,name:'mike'}`
> 那点击“新增”按钮的情况呢，这时传什么？
> 你的场景需要包含：
> 
> 1. 你的需求中新增、编辑弹窗中的表现
> 2. 为什么form属性不能满足你的需求，而需要用到slot

比如像图片中这种布局，目前form属性好像还不能做网格布局，有些可能还是一行3个输入组件，我能想到最快速的方法就是用slot
![屏幕快照 2019-08-21 上午11 09 00](https://user-images.githubusercontent.com/1159607/63399828-6088c480-c404-11e9-9628-78d14ab3c158.png)

**Comment by donaldshen** [comment]
这个使用flex布局就行了，往form注入样式。
https://femessage.github.io/el-form-renderer/#/Demo/basic
你可以在这个demo中打开console来修改样式试试。基本思路如下：
```less
.el-data-table {
  .el-form {
    display: flex;
    flex-wrap: wrap;
  }
  .el-form-item {
    width: 50%;
  }
}
```
![image](https://user-images.githubusercontent.com/19591950/63400385-2c160800-c406-11e9-9899-ae8bce80b31d.png)

**Comment by tanshiqi** [comment]
简单的可以，但是会有更复杂的布局情况，这时候自由的在slot里编辑会更加直观吧，比如：
![屏幕快照 2019-08-21 上午11 32 11](https://user-images.githubusercontent.com/1159607/63400774-a5fac100-c407-11e9-9ecb-3cc57e3da873.png)

**Comment by eviIIt** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

如果这是真实数据建议删除楼层并做好马赛克

**Comment by tanshiqi** [comment]
假的，生成的

**Comment by levy9527** [comment]
我觉得是否误会了。目前这个 slot=form 是追加，不是替换。因而，它本身跟 form 的内容是没有关系的。

从上下文推断，你以为它是内容替换。

**Comment by tanshiqi** [comment]
是的，这个我明白，常规情况下我当然知道这个是追加，但是在有些特殊情况下，我觉得可以考虑将form属性留空，然后全部的内容写在slot里面，这样自由度更大一些

**Comment by donaldshen** [comment]
> 是的，这个我明白，常规情况下我当然知道这个是追加，但是在有些特殊情况下，我觉得可以考虑将form属性留空，然后全部的内容写在slot里面，这样自由度更大一些

这样的话，你可以直接在data-table外写dialog，内容彻底自定义；然后用extraButtons来唤起并获取row数据。😁

**Comment by tanshiqi** [comment]
目前确实是这样做的，但是感觉每次都要再重复写dialog，感觉不够优雅了

**Comment by tanshiqi** [comment]
并不是每次都是完全自定义的，遇到需要很多常规字段，又想结合一下el-form-render就不行了

**Comment by donaldshen** [comment]
你在dialog里面一样可以使用el-form-renderer嘛

那以下的使用场景如何：
```html
<el-data-table>
  <template v-slot:form="{row}">
    <!-- your content -->
  </template>
</el-data-table>
```
其中row在用户点击`编辑`、`查看`时是行数据，点击`新增`时是空对象。这样能否满足你的需求

**Comment by tanshiqi** [comment]
> 你在dialog里面一样可以使用el-form-renderer嘛
> 
> 那以下的使用场景如何：
> 
> ```
> <el-data-table>
>   <template v-slot:form="{row}">
>     
>   </template>
> </el-data-table>
> ```
> 
> 其中row在用户点击`编辑`、`查看`时是行数据，点击`新增`时是空对象。这样能否满足你的需求

这样就完美了

**Comment by levy9527** [comment]
你看看这个pr，是否是你想要的 @tanshiqi 
https://github.com/FEMessage/el-data-table/pull/212

**Comment by tanshiqi** [comment]
> 你看看这个pr，是否是你想要的 @tanshiqi
> #212

太好了，就是这样的 ！

**Comment by levy9527** [comment]
已发布版本。

**Comment by optimjie** [comment]
> 已发布版本。

但是通过这种方式，编辑时数据是不能修改的。
