### ISSUE TITLE
hasEdit=false的时候，无法调用onDefaultEdit

### ISSUE THREAD

**Issue by tanshiqi** [FEMessage/el-data-table#214]
## Describe the bug
因为现在的操作栏功能（比如编辑按钮）没有办法根据当前row的某个值设置隐藏和显示，所以之前使用了extraButton里判断并添加一个编辑按钮，然后调用  onDefaultEdit(row)，并设置hasEdit: false，之前使用没有问题，1.9.0版本之后就不行了，关系到 #211 这个，似乎hasDialog是和hasNew，hasEdit，hasView关联了，那目前有什么好办法能根据条件控制操作按钮？

## Screenshots
<img width="689" alt="屏幕快照 2019-09-06 上午11 29 58" src="https://user-images.githubusercontent.com/1159607/64399062-b2367d80-d099-11e9-9711-bab2ae213ad0.png">

## environment information

补充一下：
是当hasView，hasEdit，hasNew 都设置为 false的时候，无法调用onDefaultEdit

**Comment by levy9527** [comment]
了解，用户不需要修改代码，我们还是取消 hasDialog 这个属性吧。

**Comment by eviIIt** [comment]
希望提供 _**详细**_ 一下代码

因为我也尝试使用 `hasEdit: false` 并且调用 `onDefaultEdit` 没有出现异常情况, dialog 还是正常出现了.

**Comment by tanshiqi** [comment]
```
hasView: false,
hasEdit: false,
hasNew: false,
```

**Comment by eviIIt** [comment]
使用 `edit-text` 修改编辑按钮文本, 使用 `on-edit` 用来代替 `onDefaultEdit`

感觉这两个 prop 可以定制相应的行为.

```html
<el-data-table
  edit-text="修改"
  :on-edit="myEdit"
/>

<script>
export default {
  methods: {
    myEdit(
      data, // 表单数据
      row // 当前行数据
    ) {
      // 做一些什么东西...
      // 需要返回 Promise
      return Promise.resolve()
    }
  }
}
</script>
```

不知道阁下是不是需要这样的东西 🤔

**Comment by tanshiqi** [comment]
谢谢，但是请问如何能根据当前行的某个字段显示/隐藏“修改”按钮呢？edit-text只能解决显示的名称，而不能控制显示与否，因此之前我的做法是设置hasEdit：false，然后添加一个extraButton 调用onDefaultEdit:
```
{
                    type: "success",
                    text: row => (row.status == "1" ? "显示编辑" : ""),
                    atClick: row => {
                        this.$refs.dt.onDefaultEdit(row);
                        return false;
                    }
}
```
其实也不算很完美，这样只是把文字隐藏了而已

**Comment by eviIIt** [comment]
👋Hi, v1.9.1 修复这个报错了.
