### ISSUE TITLE
关于按钮大小的问题

### ISSUE THREAD

**Issue by little-eight-china** [FEMessage/el-data-table#216]
因为看到有关按钮是写死size="small"，可以去掉么，这样的话外部可以统一控制整体样式

**Comment by levy9527** [comment]
这个其实是有历史原因的，因为经过实践，我们认为 element-ui 整体是 medium，表格的按钮是 small，看起来最合理。

所以去掉是不太可能，但增加属性去设置，倒是可以考虑。

**Comment by little-eight-china** [comment]
@levy9527 可自定义化当然是最棒的~

**Comment by levy9527** [comment]
好的，我们搞起来

**Comment by levy9527** [comment]
你好，最新的版本支持了～

**Comment by little-eight-china** [comment]
@levy9527 牛批！
