### ISSUE TITLE
Option to change languaje

### ISSUE THREAD

**Issue by gregorypilar** [FEMessage/el-data-table#22]
Hi, there is a way to change the table languaje?

**Comment by levy9527** [comment]
Well, now the table does not support this. We'll think a about it. Thanks for your attention

**Comment by evillt** [comment]
Hi @gregorypilar 

I also update a commit about translation to my PR: #44 

But I'm sorry I DO NOT know any Spanish, 'cause from your word "languaje" seems like you're a guy who speak Spanish.

Anyway, this is a component based [element-ui](https://element.eleme.io), so if you need full translation please see [element-ui/i18n](https://element.eleme.io/#/en-US/component/i18n)

P.S. It'll be happen after PR merged and version released.🤔

**Comment by levy9527** [comment]
Well，it may no plan to do this now。 I suggest you to fork this repo, and change it into your language. You can keep it up to date.
