### ISSUE TITLE
最后一页删到空，页码出现错误

### ISSUE THREAD

**Issue by donaldshen** [FEMessage/el-data-table#223]
## Describe the bug
删除完最后一页的数据时接口还是请求之前最后一页的参数

## Screenshots
![image](https://user-images.githubusercontent.com/9384365/67915615-900b3880-fbce-11e9-8399-197e21da1a47.png)

**Comment by levy9527** [comment]
这个是已知问题啊，因为query保存到url上导致的，鱼与熊掌不可兼得。

**Comment by snowlocked** [comment]
建议删除成功时计算一下`Math.floor((total-deleteSuccessCount)/size)` ,`(total-deleteSuccessCount)%size`和`currentPage`的值来判断请求哪个值
