### ISSUE TITLE
dialog里使用el-data-table,打开dialog时调用resetSearch方法报错

### ISSUE THREAD

**Issue by tangofe** [FEMessage/el-data-table#226]
## Describe the bug
dialog里使用el-data-table,  需求是打开dialog重置table数据，调用resetSearch时报错， clearSelection也是报错，想找替代方案将page和selected设置成默认值，再getList，但表单的值无法重置

## Screenshots
下面是按钮点击回调和报错信息
![image](https://user-images.githubusercontent.com/26998040/68107126-b9a1c800-ff1e-11e9-93b3-c0e65758ed74.png)
![image](https://user-images.githubusercontent.com/26998040/68107139-c9211100-ff1e-11e9-9176-df1fed364297.png)

**Comment by levy9527** [comment]
请问，table 版本是多少

**Comment by tangofe** [comment]
> 请问，table 版本是多少，是 @femessage/el-data-table 最新版本吗

尝试了几个版本，都一样，包括@femessage/el-data-table 最新版本，
最后解决方式是在this.$nextTick()里再嵌套一个$nextTick()才调用searchForm成功

**Comment by tangofe** [comment]
> > 请问，table 版本是多少，是 @femessage/el-data-table 最新版本吗
> 
> 尝试了几个版本，都一样，包括@femessage/el-data-table 最新版本，
> 最后解决方式是在this.$nextTick()里再嵌套一个$nextTick()才调用searchForm成功
是resetSearch

**Comment by donaldshen** [comment]
### plan a
https://serverless.deepexi.top/serverless-console/index.html#/material/el-data-table?file=FAQ.md
你可以参考FAQ里的类似场景：**弹窗关闭时清空选中状态**，而不是打开时

### plan b
你可以监听el-dialog的**opened**事件，在事件handler中去引用el-data-table。这样做会更保险，而不是用连续两个nextTick

**Comment by tangofe** [comment]
> ### plan a
> https://serverless.deepexi.top/serverless-console/index.html#/material/el-data-table?file=FAQ.md
> 你可以参考FAQ里的类似场景：**弹窗关闭时清空选中状态**，而不是打开时
> 
> ### plan b
> 你可以监听el-dialog的**opened**事件，在事件handler中去引用el-data-table。这样做会更保险，而不是用连续两个nextTick

这两个方案都值得考虑。还有一个问题是，弹窗里的表格选了某个分页的数据，更新路由上的，然后取消弹窗，刷新浏览器，弹窗外的表格获取数据的条件是弹窗里的，即路由上的分页

**Comment by levy9527** [comment]
> 弹窗里的表格选了某个分页的数据，更新路由上的，然后取消弹窗，刷新浏览器，弹窗外的表格获取数据的条件是弹窗里

这个可以设置属性，让弹窗里的表格设置 `save-quer=false`
