### ISSUE TITLE
不想要定制的增删改查四个操作按钮，又想增加新的操作按钮，比如 上架 下架这些，要怎么做

### ISSUE THREAD

**Issue by william-xue** [FEMessage/el-data-table#232]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by eviIIt** [comment]
Hi, 你可以通过 `extraButtons` 来定制操作栏按钮

你可以参考下面这个例子:  
https://femessage.github.io/el-data-table/#/Demo/extra-buttons

另外不想要默认提供的操作栏按钮可以设置下面几个 `props` 为 `false`: 

- `hasEdit`
- `hasView`
- `hasDelete`
