### ISSUE TITLE
末页数据删除完，getlist()请求的还是末页的数据

### ISSUE THREAD

**Issue by H-Stephen** [FEMessage/el-data-table#238]
## 描述

> 末页数据删除完，getlist()请求的还是末页的数据

![image](https://user-images.githubusercontent.com/35448255/69403022-7d4ed400-0d34-11ea-8a1f-1905a460c91f.png)

![image](https://user-images.githubusercontent.com/35448255/69403012-6e682180-0d34-11ea-97b0-587f28fd8b78.png)

## 环境版本
![image](https://user-images.githubusercontent.com/35448255/69403080-a4a5a100-0d34-11ea-8d15-c755e5d42560.png)

**Comment by levy9527** [comment]
使用 onDelete 方法是没有问题的

**Comment by H-Stephen** [comment]
看了源码onDelete是要返回一个promise，没办法自定义删除提示--有时候按照产品要求 需要特定的删除提示
