### ISSUE TITLE
url 为空时，清空 table 状态

### ISSUE THREAD

**Issue by donaldshen** [FEMessage/el-data-table#260]
**Is your feature request related to a problem? Please describe.**
有个场景是：用户选择某个角色组，table 显示对应角色的成员。但用户有可能又不选中角色，这时希望 table 置空

一般来说，没人会设了 url 后又把它清空。这不算是个 breaking change，算 feature 或 bugfix 才对。因为 url 和 data 本来就是强关联的关系，url 为空，data 也应该为空。

**Describe the solution you'd like**
如题

**Comment by levy9527** [comment]
可以这样解决：url?page=999，则这样接口返回的就是为空。一样可以得到想要的结果
