### ISSUE TITLE
table在过滤项输入,但未点击搜索,切换分页会携带一些form中的过滤项,后台es无法查询

### ISSUE THREAD

**Issue by jmzyang** [FEMessage/el-data-table#263]
## Describe the bug
[http://fionacos-deepexi-public.oss-cn-shenzhen.aliyuncs.com/attach/B06D5C00-7B64-43AC-A691-38AB8FAB23A1.png](url)

## To Reproduce
1. 满足分页数据量的列表
2. 在过滤项中随意输入一些东西,但未点击搜索
3. 换页会携带过滤项进行getlist()
4. 无法查询到数据,或者有数据后台返回为检索结果下的page页且已过滤

是设计的问题吗?

**Comment by levy9527** [comment]
目前来说是设计如此，点击下一页的时候，相当于：
- 切换下一页
- 点击查询按钮
