### ISSUE TITLE
1.16.1版本设置不了列的对齐方式

### ISSUE THREAD

**Issue by leirensheng** [FEMessage/el-data-table#264]
## Describe the bug
修改columns 或者operationAttrs中的align不起作用，最新版本出现

**Comment by levy9527** [comment]
收到，排查下看看

**Comment by lianghx-319** [comment]
可以使用 element table-columns 的 class-name 属性
https://femessage.github.io/element/#/zh-CN/component/table#table-column-attributes
![image](https://user-images.githubusercontent.com/27187946/71402783-b5fe0800-2668-11ea-95e5-2bb4466af39c.png)
