### ISSUE TITLE
改变查看按钮颜色

### ISSUE THREAD

**Issue by lixiaojie07** [FEMessage/el-data-table#27]
现在的查看按钮是灰色的 我的需求是蓝色 所有希望可以增加改变查看按钮颜色的属性

**Comment by evillt** [comment]
@lixiaojie07 
友情提示一下😂

[src/el-data-table.vue#L114](https://github.com/FEMessage/el-data-table/blob/master/src/el-data-table.vue#L114) 修改 `type` 值。

虽然想开一个 PR 新增 `props.viewType`, 但刚了解到团队貌似比较严格，还是不开比较好？🤔

**Comment by chenEdgar** [comment]
@evillt 严格是对代码质量上的。欢迎提pr 😁

**Comment by evillt** [comment]
@chenEdgar `viewType` 命名也是问题😂，哈哈

**Comment by evillt** [comment]
对此 issue 开了个 PR
用法参考 #44 🤔

**Comment by levy9527** [comment]
升级版本，解决这个问题。https://github.com/FEMessage/el-data-table/releases/tag/v1.2.3
