### ISSUE TITLE
期望折叠搜索占位能在header插槽或其他插槽之后

### ISSUE THREAD

**Issue by jmzyang** [FEMessage/el-data-table#277]
1.同时使用 折叠搜索canSearchCollapse: true 和 slot:header (涉及到禁用状态)
2.希望能区分业务逻辑和界面交互逻辑,将折叠搜索的button置于其他插槽之后
![issue](https://user-images.githubusercontent.com/26244853/72313324-faa81c80-36c5-11ea-9c95-d06b3fe73b43.png)

**Comment by levy9527** [comment]
收到！
