### ISSUE TITLE
不分页查询时候 slot-no-data 不生效

### ISSUE THREAD

**Issue by DeepenLau** [FEMessage/el-data-table#305]
## Describe the bug
1.不分页查询时候，接口没有返回 total 字段
2.slot-no-data 不生效

粗略一看，怀疑是这里的判断有bug，但不一定是这里的问题
https://github.com/FEMessage/el-data-table/blob/f12e89cabba66280d3ddb7951143e8316db9bcc7/src/el-data-table.vue#L1000
![image](https://user-images.githubusercontent.com/14030995/84244389-27a61180-ab36-11ea-9050-c7dbb356b361.png)

## Screenshots
![image](https://user-images.githubusercontent.com/14030995/84244460-43111c80-ab36-11ea-8be6-2b05402b0bbe.png)

**Comment by snowlocked** [comment]
不分页时这里已经有计算total的值了，需要检查
- 搜索条件是否为空
- dataPath路径是否正确
- 组件是否有no-data插槽
![image](https://user-images.githubusercontent.com/19562649/84741151-2ca90c00-afe1-11ea-8606-cf9126cf6653.png)
