### ISSUE TITLE
[Feature request] 希望支持 el-table 的所有事件

### ISSUE THREAD

**Issue by DeepenLau** [FEMessage/el-data-table#307]
**Is your feature request related to a problem? Please describe.**
项目中需要用到 这个 el-table 事件做某行点击后选中 checkbox
![image](https://user-images.githubusercontent.com/14030995/85983819-c083ca80-ba1a-11ea-8154-a30d2fcb8bf6.png)
初略看代码貌似不支持
![image](https://user-images.githubusercontent.com/14030995/85984016-18bacc80-ba1b-11ea-86b8-7545cd162129.png)

**Describe the solution you'd like**
期望支持所有的 el-table 的事件
比如加一个  `v-on="$listeners"`：
```js
   <el-table
        ref="table"
        v-loading="loading"
        v-bind="tableAttrs"
        :data="data"
        :row-class-name="rowClassName"
        @selection-change="selectStrategy.onSelectionChange"
        @select="selectStrategy.onSelect"
        @select-all="selectStrategy.onSelectAll($event, selectable)"
        v-on="$listeners"
      >
```

**Describe alternatives you've considered**

**Additional context**

**Comment by donaldshen** [comment]
`this.$refs.table.$refs.table.$on('row-click', handler)`
凑合用吧

**Comment by donaldshen** [comment]
或者加个 prop
```vue
<el-table
  ref="table"
  v-on="tableEventListeners"
>
```
```js
{
  props: {
    tableEventListeners: { type: Object, default() { return {} } }
  }
}
```

**Comment by DeepenLau** [comment]
> 或者加个 prop
> 
> ```
> <el-table
>   ref="table"
>   v-on="tableEventListeners"
> >
> ```
> 
> ```js
> {
>   props: {
>     tableEventListeners: { type: Object, default() { return {} } }
>   }
> }
> ```

这种更好一点
