### ISSUE TITLE
extraButtons中atClick方法的this指向问题

### ISSUE THREAD

**Issue by IMLaoJI** [FEMessage/el-data-table#317]
版本 1.20.2
问题描述
extraButtons里的自定义列操作符的atClick方法this指向问题 我需要获取当前页面的this对象，发现this指向的是self-loading-button

**Comment by levy9527** [comment]
使用箭头函数试试？

**Comment by IMLaoJI** [comment]
此贴终结，太久不写前端人傻了 感谢levy9527大佬解答。。一句话秒懂。。
