### ISSUE TITLE
获取 table 数据的请求不支持 post 方法

### ISSUE THREAD

**Issue by Jogiter** [FEMessage/el-data-table#321]
[getList](https://github.com/FEMessage/el-data-table/blob/dev/src/el-data-table.vue#L1001)

代码中默认写死了使用 get 请求。不能使用 axiosConfig 来覆盖。

希望可以通过 axiosConfig 来覆盖。或者在 props 中新增 method 字段来控制请求方式

**Comment by levy9527** [comment]
fix #322
