### ISSUE TITLE
返回嵌套数据, 新增时作为一个下拉框

### ISSUE THREAD

**Issue by mmaotai** [FEMessage/el-data-table#324]
![image](https://user-images.githubusercontent.com/60080355/96698712-0694dd80-13c0-11eb-8a0b-5f5bb94e7ac9.png)

想把track新增时作为一个下拉框, 有办法吗?

另外请求回来的数据放到哪里了?

**Comment by gd4Ark** [comment]
不好意思，我不是很明白你想要的是什么，麻烦可以详细描述你的需求吗（你的使用场景、预期）

**Comment by mmaotai** [comment]
## api返回的数据格式
```
let article = [
  {
    title: 'm1',
    content: '22',
    tag: {
      id: 1,
      name: 'java'
    }
  },
  {
    title: 'm2',
    content: '23',
    tag: {
      id: 2,
      name: 'go'
    }
  },
]
```

## 期望
![image](https://user-images.githubusercontent.com/60080355/97693019-7e0eef00-1adb-11eb-8c3d-cfed7b0f789c.png)
而不是用options的remote重新请求列表或者写死
