### ISSUE TITLE
pagination 支持 slot 自定义模式，方便支持 2048-design 的新版分页

### ISSUE THREAD

**Issue by Jogiter** [FEMessage/el-data-table#329]
[pagination-2048 design style](https://pro-hwc-gy1-2048-frontendinfra-bucket-deepexi.obs.cn-southwest-2.myhuaweicloud.com/2048-design/index.html#/zh-CN/component/pagination#2048-design-style)

项目中大量使用了组件。如果参考 UI 改版现有代码，改动较大。

是否考虑 slot pagination，以简化 UI 改版升级

**Comment by levy9527** [comment]
可以啊，尽管提pr
