### ISSUE TITLE
留言

### ISSUE THREAD

**Issue by dfjfj** [FEMessage/el-data-table#332]
作为一名后端开发人员, 使用el-data-table确实很简单, 很好用. 由衷地感谢作者以及其他contributers. 文档做得也很细致. 种花家的优秀开源软件很多,但是文档能细致, 及时更新的很少.

**Comment by levy9527** [comment]
感谢你的认可！开心！

**Comment by Skura23** [comment]
赞, 这个库值得更多关注, 在动态渲染elementui table的库里, 这个算不错的了
