### ISSUE TITLE
点击修改按钮，dialog对话框的el-select希望可以使用用filterable属性

### ISSUE THREAD

**Issue by Daaayyy71** [FEMessage/el-data-table#333]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by levy9527** [comment]
dialog 里的表单是使用 form 配置的，而表单项的属性，是可以通过 el 配置的。也即

```js
{
  type: 'select',
  el: {
    filterable: true
  }
}
```

**Comment by Daaayyy71** [comment]
`{
          type: "select",
          id: "map_id",
          label: "地图",
          options: [],
          rules: [
            {
              required: false,
              message: "请选择地图",
              trigger: "blur",
              // transform: v => v && v.trim()
            },
          ],
          remote: {
            // url: "/api/map-select?proj_id="+this.proj_id,
            url: "/api/map-all-select",
          },
          el: { placeholder: "请选择地图", filterable: true },
        },`

本来想实现的是带页面参数获取当前proj_id下的地图，但是url好像不能直接带参数查询

**Comment by Daaayyy71** [comment]
谢谢，这个问题解决了，但是还有一个小问题。
点击修改按钮后的弹框，下拉框的url怎么带页面参数查询呢

```
{
  type: "select",
  id: "map_id",
  label: "地图",
  options: [],
  rules: [
    {
      required: false,
      message: "请选择地图",
      trigger: "blur",
      // transform: v => v && v.trim()
    },
  ],
  remote: {
    // url: "/api/map-select?proj_id="+this.proj_id,
    url: "/api/map-all-select",
  },
  el: { placeholder: "请选择地图", filterable: true },
},
```
本来想实现的地图下拉框的数据为当前proj_id下的数据，但是remote中的url好像没拿到this.proj_id,

**Comment by levy9527** [comment]
呃，你要升级 el-form-renderer，修改 url 重新发送请求，在最新的版本有实现。
