### ISSUE TITLE
可以加个列选择吗?列很多时, 一屏展示不完, 展示几个自定义选中的列?

### ISSUE THREAD

**Issue by mmaotai** [FEMessage/el-data-table#339]
![image](https://user-images.githubusercontent.com/60080355/124111924-60e05500-da9c-11eb-976c-3bffca43c441.png)

**Comment by levy9527** [comment]
呃，columns 本来就是数据驱动的，你在做完列筛选后，去修改 columns 数据就好了。
```
@change = () => update data.columns
```

**Comment by mmaotai** [comment]
加上的话类似分页那种, 打开开关就可以直接用了 利好使用

**Comment by levy9527** [comment]
😂这个自己操作 columns 数据就好了呀。
