### ISSUE TITLE
请问支持全局自定义一些公共的配置么？

### ISSUE THREAD

**Issue by 974988176** [FEMessage/el-data-table#343]
我目前是通过自己定义了一个通用的组件，然后再使用这个组件的方式实现的，但是，目前遇到了个问题，我无法传递form 插槽，因为，我访问不到组件内部的row，不知道怎么封装我的组件，可以支持在我使用自己封装的组件时，还可以传递插槽，或者，如果说，可以支持全局公共配置就好了

**Comment by 974988176** [comment]
我感觉slot-form有问题，官网的例子里面的演示，也是有问题的，里面的row.address明明是有值的，但显示的确实无数据的？我亲测也是没有获取不到那个row

**Comment by Skura23** [comment]
类似于修改elementui的全局默认配置, ElDataTable的全局默认配置可以这样改:
`ElDataTable.props.paginationSize.default = 10`
