### ISSUE TITLE
请问怎么修改源码，添加额外的属性？比如分页添加背景等

### ISSUE THREAD

**Issue by 974988176** [FEMessage/el-data-table#346]
强烈建议开个交流群，方便一起交流

比如，我想要给分页组件添加背景属性，background为true，我尝试了直接在el-data-table.vue上的el-pagination上添加，但是没有作用，不知道应该怎么添加？

**Comment by levy9527** [comment]
好的，周一开搞哈。

**Comment by 974988176** [comment]
我已经实现了修改源码了哈，我是直接将组件拷贝到我项目的，然后安装了depends依赖，没有安装dev依赖

**Comment by 974988176** [comment]
不过，建议可以全局设置一下通用配置，毕竟，有些人的设置和default不一样，又不想每个组件都设置

**Comment by levy9527** [comment]
![image](https://user-images.githubusercontent.com/9384365/131341055-364a8ffd-35f5-43c6-98a7-ca16e8fa15a5.png)

已建群。

**Comment by levy9527** [comment]
> 我已经实现了修改源码了哈，我是直接将组件拷贝到我项目的，然后安装了depends依赖，没有安装dev依赖

可以的。不过一般这种全局配置，是使用element啦。我们是维护自己的一套 element，然后 table 是使用最新的源码。不过能达到目的就好啦。

**Comment by Skura23** [comment]
https://github.com/FEMessage/el-data-table/issues/343#issuecomment-987592263
