### ISSUE TITLE
你这个支持elementui的table的expand吗？

### ISSUE THREAD

**Issue by ShawshankLin** [FEMessage/el-data-table#35]
你这个支持elementui的table的expand吗？

**Comment by MiffyCooper** [comment]
el-data-table支持table的expand功能。
如下为示例 
https://codesandbox.io/s/m9or58z239

**Comment by ShawshankLin** [comment]
我想使用这种封装的方式，，用render的，但是好像不行      
  {
          type: 'expand',
          width: 30,
          render: (h, params) => {
            return h('div', [
              h(
                'div',
                {
                  style: {
                    backgroundColor: 'rgba(0, 220, 255, 0.35)',
                    'word-wrap': 'break-word'
                  }
                },
                '标题：' + params.row.title
              ),
              h(
                'div',
                {
                  style: {
                    backgroundColor: '#ffbc0061',
                    'word-wrap': 'break-word'
                  }
                },
                '内容：' + params.row.content
              )
            ])
          }
        },

**Comment by levy9527** [comment]
#36 可以看看这里的例子
