### ISSUE TITLE
增加设置form表单对齐参数

### ISSUE THREAD

**Issue by Xin-X** [FEMessage/el-data-table#37]
![Uploading 1544686692(1).png…]()
formData 表单的样式并不对其，比如我有套餐名称四个字，我还有状态两个，这种字数不通导致有长有短，换行后更是不对其，可不是增加参数设置label宽度

**Comment by Xin-X** [comment]
错别字是不是太多了，你看不懂？

**Comment by Xin-X** [comment]
> formData 表单的样式并不对其，比如我有套餐名称四个字，我还有状态两个，这种字数不通导致有长有短，换行后更是不对其，可不是增加参数设置label宽度

**Comment by levy9527** [comment]
可以设置这个
```js
 formAttrs: {labelWidth: '100px'} 
```
