### ISSUE TITLE
直接引用min.js文件，无法正常使用

### ISSUE THREAD

**Issue by Wheandis** [FEMessage/el-data-table#48]
![image](https://user-images.githubusercontent.com/8326999/52773735-9ffddf00-3076-11e9-84af-84a5bcab89c6.png)
直接引用min.js文件，无法正常使用

**Comment by levy9527** [comment]
请提供在线链接重现一下，更好地定位问题。

**Comment by evillt** [comment]
感到很抱歉,你可能无法通过 `script` 使用标签使用这个组件

因为组件依赖着有两个库`lodash.get`和`qs`

其中`qs`未发现有能直接跑在浏览器的版本

**Comment by levy9527** [comment]
现在只支持通过npm引入
