### ISSUE TITLE
增加新增、删除等按钮灵活性

### ISSUE THREAD

**Issue by chenEdgar** [FEMessage/el-data-table#49]
期望：可以通过传prop的方式自定义按钮的文字，如新增按钮默认是”新增“，可以修改为”创建“

场景：新增功能满足需求，但按钮文字描述不满足。
虽然可以通过ref引用调用内部`onDefaultNew`方法实现，但希望能支持自定义文字，少写几行代码

**Comment by levy9527** [comment]
same as #22

**Comment by donaldshen** [comment]
是否应该移除原有的三个prop：dialogNewTitle, dialogEditTitle, dialogViewTitle

然后，增加三个prop：newText(default: 新增), editText(default: 修改), viewText(default: 查看)
所有触发onDefaultNew的button的text都等于newText，弹出的modal title也是newText。edit和view同理
