### ISSUE TITLE
Error: TypeError: Cannot read property 'bindings' of null

### ISSUE THREAD

**Issue by Sotyoyo** [FEMessage/el-data-table#51]
环境: node 8.11.3
          mac mojave 10.14.3
操作: clone 项目后 进入项目 yarn 到最后一步一直waiting，所以npm install 
         然后执行 npm run doc 报warning。 然后按照提示路径访问就是空白了。所以看不到文档

![terminal_1](https://i.ibb.co/1GmFc1M/2019-02-28-10-28-05.png)
![terminal_2](https://i.ibb.co/SVrw0xc/2019-02-28-10-22-54.png)
![browser](https://i.ibb.co/KwHXd4x/2019-02-28-10-20-13.png)

**Comment by Barretem** [comment]
你需要安装这些依赖
![image](https://user-images.githubusercontent.com/47966933/53860437-ff1e9600-401b-11e9-8632-66f433208085.png)

**Comment by evillt** [comment]
有可能是`node-sass`没安装上,导致`vue-styleguidist`编译或构建失败导致

考虑一下设置npm源为淘宝源
```sh
npm config set registry https://registry.npm.taobao.org/
```

或一次性使用
```sh
npm install --registry https://registry.npm.taobao.org/
```

**Comment by levy9527** [comment]
![image](https://user-images.githubusercontent.com/9384365/54655747-03f44700-4afe-11e9-98a1-c500dc2aaa31.png)


![image](https://user-images.githubusercontent.com/9384365/54655701-df986a80-4afd-11e9-9a1f-d942b2f7b5d3.png)

![image](https://user-images.githubusercontent.com/9384365/54655709-e6bf7880-4afd-11e9-88da-14eee04bd337.png)
