### ISSUE TITLE
css problem

### ISSUE THREAD

**Issue by Sotyoyo** [FEMessage/el-data-table#52]
stories/expand.vue

![1](https://i.ibb.co/bXW5Chd/2019-02-28-10-31-19.png)
![2](https://i.ibb.co/zHdh32y/2019-02-28-10-33-05.png)

**Comment by Sotyoyo** [comment]
<style lang="stylus">
  .el-button {
    margin-left: 0px !important;
    margin-right: 10px;
  }
</style>

**Comment by levy9527** [comment]
我们的做法是，通过设置列的 minWidth，让所有按钮在同一行。目前是团队的页面规范。
