### ISSUE TITLE
调用delete接口请求yapi的时候报403

### ISSUE THREAD

**Issue by guoChopper** [FEMessage/el-data-table#56]
作者能否给个解决这种问题的方式？或者可以启动这个项目跑一遍流程,谢谢
https://github.com/YMFE/yapi/issues/642

**Comment by levy9527** [comment]
的确是有403的问题，线上会有这个问题，但自己部署的是没有的。

![image](https://user-images.githubusercontent.com/9384365/54663928-c4d5ee00-4b1d-11e9-93db-7c639813baa4.png)
