### ISSUE TITLE
pagination & i18n

### ISSUE THREAD

**Issue by fee-pg** [FEMessage/el-data-table#59]
### **Version**
1.1.1

### **OS/Browsers version**
Windows 10 - Chrome 73

### **Vue version**
2.5.17

### **Questions**

1. **pagination**: When using pagination, suppose there are 25 pieces of data, set 20/page, all data is displayed on the first page, and when the second page is clicked, there are also 25 pieces. See the document and online example page without seeing relevant explanations and solutions.
2. **i18n**: How to internationalize the operation buttons for search form and table.
![reproduce](https://user-images.githubusercontent.com/38524716/54521040-08591c80-49a5-11e9-8262-a5c14e34f003.png)

### **What is Expected?**
Maybe provide solutions and demo.

**Comment by evillt** [comment]
Hi
I feel sorry 'cuz current version doesn't support **i18n**.
And about **i18n**, we actually in considering. You can see the progress in [Projects](https://github.com/FEMessage/el-data-table/projects/1).

**Comment by fee-pg** [comment]
> Hi
> I feel sorry 'cuz current version doesn't support **i18n**.
> And about **i18n**, we actually in considering. You can see the progress in [Projects](https://github.com/FEMessage/el-data-table/projects/1).

ok, looking forward to your good news and question 2's answer?

**Comment by evillt** [comment]
🤔Is your API support `Query String Parameters`?

**Comment by levy9527** [comment]
well,  we supposed api look like this:

```js
GET /api/v1/users?page=1&size=10
```
`page=1` means  the first page, and `page=2` means the second page.

**Comment by fee-pg** [comment]
@evillt @levy9527  
thanks, i misunderstood it before and i figure it out now.

**Comment by evillt** [comment]
That's OK, we'd love to help you out.💃

**Comment by levy9527** [comment]
this issue close because duplication #22
