### ISSUE TITLE
About the row of the table

### ISSUE THREAD

**Issue by qiaoqiao10001** [FEMessage/el-data-table#60]
We can select a row of data; but cant select single row.  For another, we cant select a row of data by click the other zone of the row except the checkbox;

**Comment by levy9527** [comment]
1. table can only be selected by checkbox, not radio, because of the element-ui's design.  element-ui doesn't provide single check api.

if you wanna can select only one row, you can set props `single: true`.  Check the table's api doc.

**Comment by levy9527** [comment]
Second, why you wanna select a row by clicking the other zone? I have no idea what's your situation
