### ISSUE TITLE
按钮文字根据状态改变

### ISSUE THREAD

**Issue by PPPenny** [FEMessage/el-data-table#62]
extraButtons,配置项里面，可以设置：text字段接收多种方式吗？比如接收一个方法，执行方法，而不是让方法变成字符串显示在页面上

**Comment by evillt** [comment]
如果是函数,除了接收当前行的表格数据,还有什么参数建议吗😊

**Comment by PPPenny** [comment]
具体情况具体分析吧，参数的话，我写的时候，只用到这一行的数据。
其他的tips:
1:新增、修改和查看用的同一个form。最大的问题就是，当新增和查看的字段不一样的时候。比如：新增和修改的时候，不需要日期，会在生成这个数据的时候直接带上日期。但是查看，就要看到创建时间和更新时间了。
2:新增和修改如何动态的展示。如：选择省市，先选择了省才能选择市，这些约束如何实现。
3:url不填写，就会报个warning，如果数据不是你们要求的格式，我们要转一次才能传过去呀，强迫症，不想看到警告。
4:更新维护哈接口文档吧，感谢大佬。
5:按钮能增加其他属性不？比如类名,因为设计小姐姐并不是按照UI库来的，还有需要些伪类样式来实现。

**Comment by evillt** [comment]
😇

> **文笔水平有限请谅解.**

根据目前版本的情况,列一些可能不是最优的解决方法: (至于其他功能性的问题需要跟巨佬们请示/讨论)

2:假设你的是表单联动问题,此表格组件内使用的表单组件是团队定制版的[el-form-renderer](https://github.com/FEMessage/el-form-renderer#content)

> 可以参考一下`content[].$enableWhen`用法

```js
// 大意为 `上下九` 只会在 `province === 'Guangdong'` 时才会可操作
[
  {
    label: '上下九',
    $enableWhen: {
      province: 'Guangdong'
    }
  }
]
```

5:`headerButtons` 和 `extraButtons` 两者暂不支持其他原生属性,但支持[el-button](https://element.eleme.io/#/zh-CN/component/button#attributes)的属性

```js
{
  type: 'primary',
  text: '附加按钮1'
}
```

**Comment by lianghx-319** [comment]
数据格式是前后端约定好的。所以算是内部的业务组件。如果不对就让后端改的。
