### ISSUE TITLE
extraButtons可否改为匿名函数，因为我想让他指向所在对象获得对象属性值

### ISSUE THREAD

**Issue by xsdream** [FEMessage/el-data-table#64]
![image](https://user-images.githubusercontent.com/31870384/55418998-72c5ab80-55a6-11e9-837f-8dd49f3c1370.png)

extraButtons可否改为编译后为匿名函数，因为我想让他指向所在对象获得对象属性值，有些时候箭头函数获取vue实体不是很方便。

**Comment by levy9527** [comment]
请提供更多的信息，最好是codesandbox的在线链接
