### ISSUE TITLE
搜索表单默认提交行为

### ISSUE THREAD

**Issue by cjfff** [FEMessage/el-data-table#66]
**Describe the bug**
组件 mounted 的时候会检查搜否有渲染 `searchForm`， 有的话就会添加组件表单默认行为的语句 **`searchForm.$el.setAttribute('action', 'javascript:;')`，由于我使用的场景下是动态渲染此搜索表单的，所以这个语句并没有生效, 导致按搜索按钮表单默认行为触发, `url` 改变页面刷新。

**Screenshots**
![image](https://deepexi-moby.oss-cn-shenzhen.aliyuncs.com/table.gif)

**Expected behavior**
`searchForm` 动态渲染的场景下，按下搜索不触发表单默认行为

**environment information: **
 - Version [v1.1.1]
 - OS: [windows]
 - Browser [chrome]

**Comment by levy9527** [comment]
请提供一下复现链接，或代码示例

**Comment by cjfff** [comment]
> 请提供一下复现链接，或代码示例

这里只贴出代码的核心部分~

```js

 <el-data-table
     v-bind="dataTableConfig"
     :searchForm="userListSearchForm"
      ref="dataTable"
></el-data-table>



computed: {
    userListSearchForm() {
      const userSearchFrom = [
        {
          $type: 'input',
          label: '关键字',
          $id: 'input'
        }
      ]
     // 业务场景中会根据 `showSearch: boolean` 判断是否显示 `searchForm`
      return this.dataTableConfig.showSearch ? userSearchFrom : []
    }
}

```
