### ISSUE TITLE
希望能提供一个方法获取searchForm的值

### ISSUE THREAD

**Issue by zenghao1203** [FEMessage/el-data-table#73]
在一些业务场景里面，需要获取searchForm的值，目前不能获取

**Comment by levy9527** [comment]
请按照模板提问题。提供的信息太少，很难理解你的意思

**Comment by where20** [comment]
> 在一些业务场景里面，需要获取searchForm的值，目前不能获取

在组件上ref="elDataTable"，this.$refs.elDataTable.$refs.searchForm.getFormValue()可以获取 这是一个比较简单粗暴的方法
