### ISSUE TITLE
记录当前每个页码勾选的表格项

### ISSUE THREAD

**Issue by evillt** [FEMessage/el-data-table#75]
has PR #90 

来自同事

**Is your feature request related to a problem? Please describe.**

否

**Describe the solution you'd like**

期望有个开关 `store-checked` 之类的打开此功能

**Additional context**

_例如第一页勾选了一些_

![image](https://user-images.githubusercontent.com/19513289/57212125-41148a00-7015-11e9-8930-c83c66029e6d.png)

_切换到第二页勾选了一条_

![image](https://user-images.githubusercontent.com/19513289/57212185-74efaf80-7015-11e9-9ddc-06954d7b56fe.png)

_再切换回第一页, 依然会勾选之前勾选的_

![image](https://user-images.githubusercontent.com/19513289/57212192-7f11ae00-7015-11e9-8225-6c662c3c04e8.png)

**Comment by donaldshen** [comment]
#84
