### ISSUE TITLE
在有el-data-table的list页面中，进入edit页面,需要发起两次动作($router.push('edit'))

### ISSUE THREAD

**Issue by quixoter** [FEMessage/el-data-table#76]
**Describe the bug**
在有el-data-table的list页面中，点击新增按钮(this.$router.push({path: 'edit'}))。
1.第一次点击新增按钮后，在url路径中，在#前多加了一个多余的‘?’号，并且仍然在list页面未跳转
（路径示例:http://localhost:3000/?#/activity/assisting-activity/list）
2.第二次点击这个新增按钮，页面才跳转至edit页面(此时路径示例:http://localhost:3000/?#/activity/assisting-activity/edit)

**Screenshots**
![first-tesee1](https://user-images.githubusercontent.com/32378929/57212688-11ff1800-7017-11e9-924c-b35cf1939cc8.gif)
![image](https://user-images.githubusercontent.com/32378929/57212711-2ba05f80-7017-11e9-97d7-b97b8f207361.png)

**Expected behavior**
1.点击一次即可跳转；
2.url 去掉未知的？号

**environment information: **
bug版本 1.2.1；
之前使用1.1.1版本，无此问题

**Comment by evillt** [comment]
WIP

`<SelfLoadingButton v-bind="$attrs">` 导致最终渲染出的 html `<button type="primary">`导致触发表单提交.

正常的 `el-button` 渲染是 `button type="button"`
