### ISSUE TITLE
tree型table拖拽和普通table拖拽

### ISSUE THREAD

**Issue by Jack-rainbow** [FEMessage/el-data-table#77]
**期待的功能**
表格拖拽(tree型table拖拽/普通table拖拽)

**OS /浏览器版本**
win10 / chrome 74

**Vue版本**
2.5.17

**为什么提出功能需求？**
希望特定场景满足tree型table拖拽和普通table拖拽

**考虑及目前做法**

1. 考虑过iview-admin、D2-admin、element-ui及data-table 实现tree拖拽，结果以失败告终。失败原因：以上组件都是同级渲染DOM结构，而sortTable是拖拽时获取拖拽子节点的父节点，因为DOM元素是同级渲染，所以我找不到一个table所有行的不同点来取出拖拽行下的所有子节点(当然不排除我写法错误)。

1. 目前的做法，采用了递归VueDraggable组件，但我认为这不是最优的解决方案。 

**期望结果**
tree型table及普通table拖拽，如果可以留言发表下实现tree型多级拖拽table思路那么就太完美了。Thank~~

**可供参考组件**

[Vue.Draggable](https://github.com/SortableJS/Vue.Draggable)
  组件拖拽demo
   [Nested draggable](https://sortablejs.github.io/Vue.Draggable/#/nested-example)

**Comment by levy9527** [comment]
你好，从你的描述中，看出你是个实践派，非常靠谱。

这个功能其实我们内部也有声音要实现这个需求，但放到el-data-table里，需要寻求一个最佳实践，这并不仅仅是关乎前端，还包含后端、以及产品设计，故这个问题可能需要较长的时间才能你的结论

**Comment by xlz26296** [comment]
树表格的拖动最主要的是要保证数据的同步，感觉你这需求可以参考这个的实现哈 https://xuliangzhan.github.io/vxe-table/#/table/other/sortableRow

**Comment by levy9527** [comment]
现在来看，如果要做拖拽，还是自己写 table 吧，这个需求超出 el-data-table 的职能范围了。
