### ISSUE TITLE
不传入url 仅传入列表数据做展示用

### ISSUE THREAD

**Issue by MiaosisDD** [FEMessage/el-data-table#79]
## 问题：
项目中会遇到 从另一个表格中筛选出数据进行展示的需求
![image](https://user-images.githubusercontent.com/23629177/57277762-64a00900-70d7-11e9-865c-8ac6f36e4135.png)

这些数据是不需要请求的，这时再用el-data-table就不太合适了
尝试过直接访问 `this.$refs.table.data` 去直接修改数据源，但感觉不太合适

## 期望：
可以新增一个方法 直接更新列表数据
或者新增一个配置 可以填入列表数据

**Comment by levy9527** [comment]
其实这个功能，可以直接使用el-table来做，而不是往el-data-table里加功能。

另外，关于这种crud，其实可以另有专门的组件来实现，React社区已经有相关的例子，也即NoForm的Repeater。

后续计划实现一个vue版本的。
