### ISSUE TITLE
headerButtons的atClick只能返回一个Promise，，没有兼容普通函数

### ISSUE THREAD

**Issue by MJmajiong** [FEMessage/el-data-table#80]

**Comment by donaldshen** [comment]
什么叫“没有兼容普通函数”？请描述你想要的效果。
如果你直接`return false`也可以起到不刷新表格的结果。atClick的返回值会被`Promise.resolve`包装一层再处理

**Comment by levy9527** [comment]
v1.0.0版本api全面promise化，设计如此😂
