### ISSUE TITLE
重置搜索框内容时，url携带多余参数

### ISSUE THREAD

**Issue by Jack-rainbow** [FEMessage/el-data-table#86]
**Describe the bug**
重置搜索框内容时，url携带多余参数`&`

**environment information**
OS /浏览器版本
win10 / chrome 74

**vue（Version）**
2.5.17

**el-data-table（Version）**
 1.1.1

**Screenshots**
![el-data-table(reset重置携带多余参数)](https://user-images.githubusercontent.com/20368037/57505069-885a8d80-7329-11e9-8eea-3f00d7737167.gif)

**Expected behavior**
 重置搜索框内容时，url不携带多余参数`&`

**Comment by donaldshen** [comment]
![image](https://user-images.githubusercontent.com/19591950/57760746-cc390280-772e-11e9-9a8b-0ad51dd99e8d.png)
